from posidonius.constants import *
from posidonius.integrator.common import Integrator

class Ias15(Integrator):
    def __init__(self, time_step, recovery_snapshot_period, historic_snapshot_period, universe):
        super(Ias15, self).__init__(time_step, recovery_snapshot_period, historic_snapshot_period, universe)
        self._data['n_particles'] = universe._data['n_particles']
        self._data['integrator_iterations_max_exceeded'] = 0
        self._data['time_step_last_success'] = 0.
        #self._data['b'] = [[0.,] *  3*MAX_PARTICLES,] * 7
        self._data['b_0'] = [0.,] *  3*MAX_PARTICLES
        self._data['b_1'] = [0.,] *  3*MAX_PARTICLES
        self._data['b_2'] = [0.,] *  3*MAX_PARTICLES
        self._data['b_3'] = [0.,] *  3*MAX_PARTICLES
        self._data['b_4'] = [0.,] *  3*MAX_PARTICLES
        self._data['b_5'] = [0.,] *  3*MAX_PARTICLES
        self._data['b_6'] = [0.,] *  3*MAX_PARTICLES
        #self._data['br'] = [[0.,] * 3*MAX_PARTICLES,] * 7
        self._data['br_0'] = [0.,] * 3*MAX_PARTICLES
        self._data['br_1'] = [0.,] * 3*MAX_PARTICLES
        self._data['br_2'] = [0.,] * 3*MAX_PARTICLES
        self._data['br_3'] = [0.,] * 3*MAX_PARTICLES
        self._data['br_4'] = [0.,] * 3*MAX_PARTICLES
        self._data['br_5'] = [0.,] * 3*MAX_PARTICLES
        self._data['br_6'] = [0.,] * 3*MAX_PARTICLES
        #self._data['g'] = [[0.,] *  3*MAX_PARTICLES,] * 7
        self._data['g_0'] = [0.,] *  3*MAX_PARTICLES
        self._data['g_1'] = [0.,] *  3*MAX_PARTICLES
        self._data['g_2'] = [0.,] *  3*MAX_PARTICLES
        self._data['g_3'] = [0.,] *  3*MAX_PARTICLES
        self._data['g_4'] = [0.,] *  3*MAX_PARTICLES
        self._data['g_5'] = [0.,] *  3*MAX_PARTICLES
        self._data['g_6'] = [0.,] *  3*MAX_PARTICLES
        #self._data['e'] = [[0.,] *  3*MAX_PARTICLES,] * 7
        self._data['e_0'] = [0.,] *  3*MAX_PARTICLES
        self._data['e_1'] = [0.,] *  3*MAX_PARTICLES
        self._data['e_2'] = [0.,] *  3*MAX_PARTICLES
        self._data['e_3'] = [0.,] *  3*MAX_PARTICLES
        self._data['e_4'] = [0.,] *  3*MAX_PARTICLES
        self._data['e_5'] = [0.,] *  3*MAX_PARTICLES
        self._data['e_6'] = [0.,] *  3*MAX_PARTICLES
        #self._data['er'] = [[0.,] * 3*MAX_PARTICLES,] * 7
        self._data['er_0'] = [0.,] * 3*MAX_PARTICLES
        self._data['er_1'] = [0.,] * 3*MAX_PARTICLES
        self._data['er_2'] = [0.,] * 3*MAX_PARTICLES
        self._data['er_3'] = [0.,] * 3*MAX_PARTICLES
        self._data['er_4'] = [0.,] * 3*MAX_PARTICLES
        self._data['er_5'] = [0.,] * 3*MAX_PARTICLES
        self._data['er_6'] = [0.,] * 3*MAX_PARTICLES
        self._data['at'] = [0.,] *  3*MAX_PARTICLES
        self._data['x0'] = [0.,] *  3*MAX_PARTICLES
        self._data['v0'] = [0.,] *  3*MAX_PARTICLES
        self._data['a0'] = [0.,] *  3*MAX_PARTICLES
        #self._data['sb'] = [[0.,] *  3*MAX_PARTICLES,] * 7
        self._data['sb_0'] = [0.,] *  3*MAX_PARTICLES
        self._data['sb_1'] = [0.,] *  3*MAX_PARTICLES
        self._data['sb_2'] = [0.,] *  3*MAX_PARTICLES
        self._data['sb_3'] = [0.,] *  3*MAX_PARTICLES
        self._data['sb_4'] = [0.,] *  3*MAX_PARTICLES
        self._data['sb_5'] = [0.,] *  3*MAX_PARTICLES
        self._data['sb_6'] = [0.,] *  3*MAX_PARTICLES
        #self._data['sbr'] = [[0.,] * 3*MAX_PARTICLES,] * 7
        self._data['sbr_0'] = [0.,] * 3*MAX_PARTICLES
        self._data['sbr_1'] = [0.,] * 3*MAX_PARTICLES
        self._data['sbr_2'] = [0.,] * 3*MAX_PARTICLES
        self._data['sbr_3'] = [0.,] * 3*MAX_PARTICLES
        self._data['sbr_4'] = [0.,] * 3*MAX_PARTICLES
        self._data['sbr_5'] = [0.,] * 3*MAX_PARTICLES
        self._data['sbr_6'] = [0.,] * 3*MAX_PARTICLES
        #self._data['sg'] = [[0.,] *  3*MAX_PARTICLES,] * 7
        self._data['sg_0'] = [0.,] *  3*MAX_PARTICLES
        self._data['sg_1'] = [0.,] *  3*MAX_PARTICLES
        self._data['sg_2'] = [0.,] *  3*MAX_PARTICLES
        self._data['sg_3'] = [0.,] *  3*MAX_PARTICLES
        self._data['sg_4'] = [0.,] *  3*MAX_PARTICLES
        self._data['sg_5'] = [0.,] *  3*MAX_PARTICLES
        self._data['sg_6'] = [0.,] *  3*MAX_PARTICLES
        #self._data['se'] = [[0.,] *  3*MAX_PARTICLES,] * 7
        self._data['se_0'] = [0.,] *  3*MAX_PARTICLES
        self._data['se_1'] = [0.,] *  3*MAX_PARTICLES
        self._data['se_2'] = [0.,] *  3*MAX_PARTICLES
        self._data['se_3'] = [0.,] *  3*MAX_PARTICLES
        self._data['se_4'] = [0.,] *  3*MAX_PARTICLES
        self._data['se_5'] = [0.,] *  3*MAX_PARTICLES
        self._data['se_6'] = [0.,] *  3*MAX_PARTICLES
        #self._data['ser'] = [[0.,] * 3*MAX_PARTICLES,] * 7
        self._data['ser_0'] = [0.,] * 3*MAX_PARTICLES
        self._data['ser_1'] = [0.,] * 3*MAX_PARTICLES
        self._data['ser_2'] = [0.,] * 3*MAX_PARTICLES
        self._data['ser_3'] = [0.,] * 3*MAX_PARTICLES
        self._data['ser_4'] = [0.,] * 3*MAX_PARTICLES
        self._data['ser_5'] = [0.,] * 3*MAX_PARTICLES
        self._data['ser_6'] = [0.,] * 3*MAX_PARTICLES
        self._data['dangular_momentum_dtt'] = [0.,] *  3*MAX_PARTICLES
        self._data['dangular_momentum_dt0'] = [0.,] *  3*MAX_PARTICLES
        self._data['angular_momentum0'] = [0.,] *  3*MAX_PARTICLES
        self._data['csx'] = [0.,] * 3*MAX_PARTICLES
        self._data['csv'] = [0.,] * 3*MAX_PARTICLES
        self._data['css'] = [0.,] * 3*MAX_PARTICLES
        self._data['s'] = [0.,] * 9

